
import React from 'react';

interface MarkdownRendererProps {
  content: string;
  className?: string;
  headingFont?: string;
  bodyFont?: string;
}

const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ 
    content, 
    className,
    headingFont = 'inherit',
    bodyFont = 'inherit'
}) => {
  // Normalize line endings and split
  const lines = content.replace(/\r\n/g, '\n').split('\n');

  return (
    <div className={`space-y-1 ${className}`}>
      {lines.map((line, index) => {
        const trimmed = line.trim();

        // Empty lines
        if (trimmed === '') {
          return <div key={index} className="h-4"></div>;
        }

        // HEURISTIC: Section Headers
        const isMcqOption = /^[A-Ea-e][\)\.]\s+/.test(trimmed) || /^\([A-Ea-e]\)\s+/.test(trimmed);
        const isSectionHeader = 
            !isMcqOption && (
                trimmed.match(/^(SECTION|PART)\s+[A-Z0-9]+/i) || 
                (trimmed === trimmed.toUpperCase() && trimmed.length < 50 && trimmed.length > 3 && !trimmed.match(/^\d+\./))
            );

        // CLEANUP: Strip unexpected artifacts
        const cleanLine = line.replace(/\*\*/g, '').replace(/###/g, '').replace(/##/g, '');

        if (isSectionHeader) {
          return (
            <h3 key={index} style={{ fontFamily: headingFont }} className="text-lg font-bold mt-6 mb-3 uppercase tracking-wide text-gray-900">
                {cleanLine}
            </h3>
          );
        }

        // Horizontal Rules
        if (trimmed.match(/^(-{3,}|={3,}|_{3,})$/)) {
            return <hr key={index} className="my-6 border-gray-300" />;
        }

        // Normal Text - Unicode Math Safe
        // whitespace-pre-wrap is CRITICAL for vertical fractions generated by AI
        return (
          <p key={index} style={{ fontFamily: bodyFont }} className="whitespace-pre-wrap leading-relaxed text-gray-800 text-base">
            {cleanLine}
          </p>
        );
      })}
    </div>
  );
};

export default MarkdownRenderer;
